import Providers from "../lib/Providers";
import Cproviders from "@/lib/Chakraprovider";
import Footer from "../components/section/Footer";
import Navbar from "../components/section/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider, auth } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();

  return (
    <ClerkProvider>
      <Providers>
        <html lang="en">
          <Cproviders>
            <body>
              <Navbar userId={userId as string} />
              {children}
              <Footer />
            </body>
          </Cproviders>
        </html>
      </Providers>
    </ClerkProvider>
  );
}
